version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
     - dependency-name: "rsc.io/quote"
       versions: [ ">= 1.9.0" ]
     - dependency-name: "github.com/fatih/color"
       update-types: ["version-update:semver-minor"]
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
     - dependency-name: "rsc.io/quote"
       versions: [ ">= 1.9.0" ]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
     - dependency-name: "*"
       update-types: ["version-update:semver-minor"]
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "monthly"

