version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
     - dependency-name: "rsc.io/quote"
       versions: [ ">= 1.9.0" ]
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
