name: Body moving
on: workflow_dispatch

permissions:
  contents: read

jobs:
  body-moving:
    name: We be body moving
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2.1.0
